// <auto-generated />
using KodisApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KodisApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("KodisApi.Data.LoginSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Expires")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotebookUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshTokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RefreshedDate")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RevokedDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Expires");

                    b.HasIndex("NotebookUserId");

                    b.ToTable("LoginSessions");
                });

            modelBuilder.Entity("KodisApi.Data.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotebookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("KodisApi.Data.Notebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EditPasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpireDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotebookUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewPasswordHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpireDate");

                    b.HasIndex("NotebookUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Notebooks_NotebookUserId_Main")
                        .HasFilter("\"IsMain\" = TRUE");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("KodisApi.Data.NotebookUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastLoginDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginMethod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ModifiedDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Picture")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sub")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("\"UserName\" IS NOT NULL");

                    b.HasIndex("LoginMethod", "Sub")
                        .IsUnique()
                        .HasFilter("\"Sub\" IS NOT NULL");

                    b.ToTable("NotebookUsers");
                });

            modelBuilder.Entity("KodisApi.Data.LoginSession", b =>
                {
                    b.HasOne("KodisApi.Data.NotebookUser", "NotebookUser")
                        .WithMany("LoginSessions")
                        .HasForeignKey("NotebookUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotebookUser");
                });

            modelBuilder.Entity("KodisApi.Data.Note", b =>
                {
                    b.HasOne("KodisApi.Data.Notebook", "Notebook")
                        .WithMany("Notes")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notebook");
                });

            modelBuilder.Entity("KodisApi.Data.Notebook", b =>
                {
                    b.HasOne("KodisApi.Data.NotebookUser", "NotebookUser")
                        .WithMany("Notebooks")
                        .HasForeignKey("NotebookUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NotebookUser");
                });

            modelBuilder.Entity("KodisApi.Data.Notebook", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("KodisApi.Data.NotebookUser", b =>
                {
                    b.Navigation("LoginSessions");

                    b.Navigation("Notebooks");
                });
#pragma warning restore 612, 618
        }
    }
}
